# ============================================================================
# SAFEHAVEN AI - BACKEND LOGIC
# PART 4B: REPORT GENERATOR STUB
# ============================================================================

from fpdf import FPDF
import os

def generate_inspection_report(property_address: str, inspection_data: dict) -> str:
    """
    Generates a PDF summary of the inspection.
    
    Args:
        property_address (str): Name/Address of property.
        inspection_data (dict): Aggregated findings.
        
    Returns:
        str: Path to the generated PDF file.
    """
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt=f"SafeHaven AI Inspection Report", ln=1, align='C')
    
    pdf.set_font("Arial", 'I', 12)
    pdf.cell(200, 10, txt=f"Property: {property_address}", ln=1, align='C')
    pdf.line(10, 30, 200, 30)
    
    # Body
    pdf.ln(20)
    pdf.set_font("Arial", '', 12)
    
    pdf.cell(200, 10, txt="Inspection Summary:", ln=1)
    
    for key, value in inspection_data.items():
        pdf.cell(200, 10, txt=f"- {key}: {value}", ln=1)
        
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(200, 10, txt="Generated by SafeHaven AI (Powered by Snowflake Cortex)", ln=1)
    
    # Output
    # In a real Snowflake app, this would write to /tmp or a Stage
    output_path = os.path.join(os.path.dirname(__file__), "inspection_report.pdf")
    pdf.output(output_path)
    
    return output_path
